name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        epamdz:
          description: 'Any variable'
          required: true
          default: 'EPAM-GIT'

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py

        - name: 1.2 Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

        - name: 1.3 ADD VARIABLE AND DATE TO MY ARTIFACT
          run: |
            mkdir -p ${{ github.workspace }}/artifact
            echo ${{ github.event.inputs.epamdz }} ${{ steps.date.outputs.date }} > ${{ github.workspace }}/artifact/homework.txt


        - name: 1.4 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2

        - name: 1.5 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: my-artifacts
              path: |
                /home/runner/work/devops-school/devops-school/log.md
                ${{ github.workspace }}/artifact/homework.txt


